---
title: "Twitter Data"
type: "challenge"
depends: "rock-paper-scissors"
description: "Write multiple methods to parse a compound data structure to return values needed"
ignore:
- "twitter-data.md"
