# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea4d33f09d1d914e0c295503fa663d0c84356b63bf06777e04289f3b88912b886f79536d572545287853f72f844caf23d58ed9ea581c518422412781ab8e2016

test:
  secret_key_base: 6ee3e5a67b62f2d2293d37a87cf4169826d1b1d6d0bfb6e248ff5a0c8c4137efd73c9bdf23f468c007a85734d3ce3a814a1e5d9df38cb5260cd62eb2f9c133e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
