---
title: "Automat.js"
type: "challenge"  # challenge, exercise, article, tutorial, video
description: "Simulate an old-school Automat lunch counter."
tags: "javascript, arrays"
ignore:
- "automat-js.md"
