---
title: "JS Fetch Challenge"
type: "challenge"  # challenge, exercise, article, tutorial, video
description: "Practice using the JavaScript Fetch API."
tags: "javascript, fetch"
ignore:
- "images/*"
- "text/*"
- "js-fetch-challenge.md"
