---
title: "User Account Validator"
type: "exercise"  # challenge, exercise, article, tutorial, video
description: "Learn to create classes that raise exceptions, and handle them."
tags: "ruby, exceptions"
ignore:
- "user-account-validator.md"
