---
title: "ToDo.js"
type: "challenge"  # challenge, exercise, article, tutorial, video
description: "Create a ToDo list in HTML and JavaScript."
tags: "javascript, system-check"
ignore:
- "todo-js.md"
