---
title: "React Quiz Sinatra"
type: "challenge"
description: "Build a quiz application in React"
tags: "javascript, react, sinatra"
ignore:
- "node_modules/"
- "react-quiz-sinatra.md"
- "react/coverage"
